# SQLite. Versions 3.8.0 and up are supported.
#   gem install postgresql
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'postgresql'
#
default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development

production:
  <<: *default
  database: db/production
